### ISSUE TITLE
Fluor can't detect active application correctly for winehq.

### ISSUE THREAD

**Issue by zhengcan** [Pyroh/Fluor#21]
I'm using winehq to play windows game in macOS.
Unfortunately, it can't detect winehq application as active application.

**Comment by Pyroh** [comment]
Could you please tell me which version of wine you are using ?

**Comment by supersophie** [comment]
Does not detect running WINE app. In this case a game called EVE Online.
I don't know the WINE version because CCP ( EVE Online publishers ) only list the WINE version as "Latest". 

However I know their last release was 2.6-195-g4b874727-ccp-master098. So the latest is greater that this.

Note: I am not the OP.
