### ISSUE TITLE
Sparkle updates?

### ISSUE THREAD

**Issue by danielcompton** [Pyroh/Fluor#36]
It could be good to add a Sparkle updater so that people can get notified about new updates. Not sure how difficult this is though?

**Comment by Pyroh** [comment]
Sometimes universe makes things great. You want Sparkle ? I'm already implementing it and everything seem to work this morning. That's why I invite you to download the last Fluor update on the [new Fluor website](https://fluorapp.net). 

The sad part is you won't experience Sparkle update before the next version 😧
