### ISSUE TITLE
First run after brew install shows SSL error

### ISSUE THREAD

**Issue by marcoboerner** [Pyroh/Fluor#64]
I installed Fluor using Homebrew and as I started it the first time I got a SSL connection error. A) this seems to be a bug, B: WHY is Fluor trying to connect to anything using SSL or any other way?

**Comment by Pyroh** [comment]
It's just trying to retrieve the release notes from a website that no longer exists since the data center burnt.
There used to be some analytics in Fluor to try and (roughly) count its users but it's been removed since. If you have some doubts you can check the code.

So, it's not really a bug and I don't want your data 😉
