### ISSUE TITLE
Pseudo Touchbar

### ISSUE THREAD

**Issue by BrianSemiglia** [Pyroh/Fluor#8]
It'd be cool if holding _fn_ would reveal a view (maybe like the command-tab menu) at the bottom of the screen, displaying the current mappings of the function keys. This could give all the folks with older machines a taste of the cutting edge!

**Comment by Pyroh** [comment]
Fluor doesn't manage the fn key itself. In fact it still works as usual and you can toggle the function keys behaviour by holding the fn key.
I won't add the view you're talking about because it may be annoying for a lot of people (including me).

If you still want to see the Touchbar onscreen use this app: [TouchBarDemoApp](https://github.com/bikkelbroeders/TouchBarDemoApp) 😉

**Comment by BrianSemiglia** [comment]
Oh nice. Thanks for the tip!
